### ISSUE TITLE
Response codes

### ISSUE THREAD

**Issue by montogeek** [Raathigesh/Atmo#25]
It would be great to support all HTTP Response Codes, I could add it using https://developer.mozilla.org/en/docs/Web/HTTP/Response_codes as reference :)

**Comment by Raathigesh** [comment]
That would be great. Would you like to add these and send a PR ?

**Comment by montogeek** [comment]
Sure!

**Comment by Raathigesh** [comment]
Sorry, it took a while to publish the release. Got caught up with work. Released this change in [v0.11.0](https://github.com/Raathigesh/Atmo/releases/tag/v0.11.0). There was a small change to add a scroll bar to the dropdown since in small screen it was overflowing beyond the page height. All good now. Thank you for spending time with this PR!
